Use Nuxt runtime config
moritzsternemann/vue-plausible pull request #11
Opened 2021-05-25 17:19 UTC by ambroisemaupate

Fixes #10 

This would allow changing Plausible options over different environments (dev, testing, production) using [Nuxt `runtimeConfig`](https://nuxtjs.org/docs/2.x/directory-structure/nuxt-config#runtimeconfig).

2021-06-08 11:17 UTC, moritzsternemann commented
Thanks for the PR! I'm super busy right now, I'll take a look at it towards the end of the week 😄

2021-07-07 19:26 UTC, moritzsternemann requested changes
@ambroisemaupate sorry again this took me so long. Just some tiny comments and be can get this merged!

2021-07-07 19:26 UTC, moritzsternemann commented on src/nuxt-module.ts
> +    ...nuxt.options.runtimeConfig?.plausible
please use `this` here instead of destructuring it above

2021-07-07 19:26 UTC, moritzsternemann commented on src/nuxt-plugin.ts
> +    ...context.$config?.plausible
Do we really need this? Options are always passed from the module and runtimeConfig is added there.

2021-07-12 11:54 UTC, ambroisemaupate commented
Hi @moritzsternemann 

Thanks for your suggestions, PR has been updated.

2021-07-12 12:46 UTC, moritzsternemann approved these changes

2021-07-12 12:46 UTC, moritzsternemann commented
Thanks again! I'll publish a new release in a few minutes 🙂

2021-07-12 12:46 UTC, merged

2021-07-12 13:35 UTC, ambroisemaupate commented
@moritzsternemann Thanks,

I just found out that the right override to do was in the **plugin**, not in the module. Everything which happen in module is in build-time.

Sorry, I'll push a new PR as soon as possible.

2021-07-12 13:36 UTC, moritzsternemann commented
Oh you are totally right, I didn't think of that. Thanks for handling this!